apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: echo-server
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Jelleby/open-ecosystem-challenges.git
        revision: HEAD
        directories:
          - path: adventures/01-echoes-lost-in-orbit/beginner/manifests/overlays/*
  template:
    metadata:
      name: echo-server-{{path.basename}} # Use the basename of the path as a suffix
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Jelleby/open-ecosystem-challenges.git
        targetRevision: HEAD
        path: adventures/01-echoes-lost-in-orbit/beginner/manifests/overlays/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: echo-{{path.basename}} # Use the basename of the path as part of the namespace
      syncPolicy:
        automated:                        
          enabled: true                   # Turn on automated syncing
          prune: true                     # Allow deletion of resources no longer defined in Git                 
          selfHeal: true                  # Automatically correct drift from the desired state in Git 
        syncOptions:
          - CreateNamespace=true
